apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-local-persistent
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: zfs.csi.openebs.io
parameters:
  fstype: zfs
  poolname: tank
  datasetParentName: k8s
  recordsize: "128k"
  compression: "zstd"
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
