apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: minio
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "minio.network.rafaeltab.com"
      secretName: minio_network_rafaeltab_com_tls
  rules:
    - host: "minio.network.rafaeltab.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-tenant-console
                port:
                  number: 9001
