apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: ">=5.0.0" # pick a specific chart version you trust
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    mode: standalone
    replicas: 1

    image:
      repository: minio/minio
      tag: RELEASE.2025-09-07T16-13-09Z
      pullPolicy: IfNotPresent

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 2Gi

    service:
      type: ClusterIP
      port: 9000
      consolePort: 9001

    ingress:
      enabled: false
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
        traefik.ingress.kubernetes.io/router.tls: "true"
      path: /
      hosts:
        - minio.network.rafaeltab.com
      tls:
        - hosts:
            - "minio.network.rafaeltab.com"
          secretName: minio-network-rafaeltab-com-tls

    persistence:
      enabled: true
      existingClaim: "" # leave empty if you want Helm to create the PVC
      size: 50Gi
      storageClass: "zfs-local"
      accessModes:
        - ReadWriteOnce

    # Credentials via existing secret
    credentials:
      existingSecret: minio-creds
      rootUserKey: rootUser
      rootPasswordKey: rootPassword

    # Health and probes
    livenessProbe:
      initialDelaySeconds: 20
    readinessProbe:
      initialDelaySeconds: 10

    # Optional: set security context if needed for ZFS permissions
    podSecurityContext:
      fsGroup: 1000
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
