apiVersion: v1
kind: Secret
metadata:
    name: minio-creds
    namespace: minio
type: Opaque
stringData:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:nVTzDUVICN8X,iv:8uyHP8rBl54nFl7shtfz7Qp7CfvykcS2kaKUoE5VDIk=,tag:EcwLMPdh3GE6FnrRZXFIcA==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:wiqqYdE5U/o79Q8fAJZmz5Q4oDUVwXMPsxdX9RfuXmE=,iv:iW+u9WBIa/I2qkEJhdajYtDrd1bNb39R3wF7AeUkNZk=,tag:wv5xrXG4/Vo4H4civ+xOoQ==,type:str]
sops:
    lastmodified: "2025-09-28T20:14:10Z"
    mac: ENC[AES256_GCM,data:tgYYLWyfW2tlAPDoWu6gnIoDZhkzlhxD0HJboJ0UU1KNB8LJPacobIjKZUWbQoedtQSDyDsBs+/nw9Z13bRzyn8pcM//7WDD3th+lNob2fatWzvyy1yitlT5txs+53sDUQaTSqzlAGhorbwbQWd9+FKd697wyt4FV/FCJs8vxJA=,iv:1sZsag9Id5ZO7ia6C6Unjr3EKCSMGFOMY4dcNOIrcIc=,tag:3Gq95r6rQe/PBzNCQnvD5w==,type:str]
    pgp:
        - created_at: "2025-09-28T20:14:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNARAAoB8rQtUM02vX4x3Axx9IxwEBAIGFIPZcIt09pfzZkSN0
            rCgtyUdC1kXHnQh1wg7v1k6RixyKpk0zNM0v6QlijLJxJ7b2r2zKXAiVjiHn3UoO
            ZgDRZv+gb/Zppg/IZYw1FyrWxLvVcRdV/KKGxhD/IdviAfOGTiXER9SLzF0wG5XW
            ZyxuWfb/T42GxtOE/3CXt1Z8poDKbe9v3JuDpt43PGBQBSgDsREP+fAJehkdG9WT
            oIBan9C0desZlvZXZTelGXYg752ppVEWZH5GeL+3hiyNFOLJ9THN5sLPJE8YB7FW
            /lVaOsxof6YE9MkoSJzk1McG7goZASv60e7ZrxvqBMzOVfPb4BZ/SzAS8KUCZPuh
            LCJkxRM+ecPLv6pgDj6zK0wbeh5NmGqeBfot0PCRvNjz27/gdL3sxyr0HhOrP/aX
            479/UDRFoFXK0BWJ4y8ByEeAmCkoi9QsPuZ6qrahQ2zKOePY7P0CjT5mOpc3e5Y8
            BuuvsXGjvL27uQiGrrNNGgPvkiWpnMnAXuzYX3g9d5mk+nuzOGG9pqDSwHPHGuft
            lSma4y6DlffUMB49smXhT21yqSPqoTNMAjp6vsJJ9v/q5X6h9XeSexioDD9amMV/
            tYU5WBN/RTPHMbidblpl/n7cKQVyvrZSfMgi6TAtPi2FfUhEem6A3i7JAN8BbYbS
            XgHn49+UUROwE47ln2g8pvMzlPA0C4dRwYATUJrBVNGhDXHj58ZKpy6uVWxzcRw8
            MVvujiwykpSnZ9OEJ9r3w0hiq2CvCKLfY29v+GPCO2zhawjp8OX+3xERUkBlxmQ=
            =UPfI
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
