apiVersion: v1
kind: Secret
metadata:
    name: minio-creds
    namespace: minio
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:z+Pvoyo8trMda8fS6mR+zyHlNKtL2TlghqLNVQS00Yh6dtdL52mxIY23t193bHWEssNryWZyNvvY+Jd1365G8LbPD/AZqXUvDgp07SqEY2tfge3XC+Cy,iv:syb29IzkP1k5e1G0pl0NWOGsilGukCsgVRyP5LkEg9M=,tag:SM95Pp8Rw1dFB7v79EQyJA==,type:str]
sops:
    lastmodified: "2025-10-01T14:36:46Z"
    mac: ENC[AES256_GCM,data:JJbzqKQREndeGZRF36RH/twKfEbwal++iTpeO3kTwtolXl0pvZ1ecWskUEeDUYgx7Zm7trfWW5ywFWlABgGHAd+xSAVefg+fWoJbOw1tuz8842dhiqERDMheX5ljtITjM7lDpE2Uau834odj/0HLGY5CXpH81JAcuOrSXgNsDiM=,iv:MSIkRN+MOryXp++gzLa7ONeGwu/VmWuymjB2gpgKlpo=,tag:NSf8WXZCjjVbXSM6Nc7O9w==,type:str]
    pgp:
        - created_at: "2025-10-01T14:36:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNAQ/8C9IdILXZeljctuGKdXi+ECHX1nUJlxLsVHpvOtvz8uOt
            LeW6q318MTHAO9Z0TjMsZFlxuAoeYi8ITUIdOcO6amR1IrQ1D2sSWMPlKIHJcySB
            MqrQMxN1DbeDz8CYvpagPFUI5OfCXvKr8HUJbIDUMsmQA0PyVJ9y5pbkvdi2coNR
            pmMwkm864kTsW8l7VW6iIvs2eyUSC63spyHLGLQU355T3DsCRbrxErdOoq1upWyo
            rKKXvXFhHuhLuPEIQXahMhMy4pkhzQ+lOCZ3n7uRjS0UhKj3rrz3U+OWtdzto+U9
            PtCcE3w2CBD/kQylzNuMQxp1xeXBqoapaqt7wEymEXHVMxkuOBejUq1arbOmdk4T
            V4jRxHTh1j8ZCRfNJybLC8eALQEzeM0unkBOHrQlbRgWYs7rSIpvXNAt3lp1LrXg
            nQRugh+7QX/UuQw2HnxGMJWRTpoMoqlwnAB63DbQfSnw/wfXpgrGq4+l6zPivx/U
            eTwjVLXI5HTDUMdMo/NIjVhmPQmnRI/q8StW5bTreDf0eVGqvujkJuzjkPbV7YKz
            mtrGoofpjJYT1sVLCn/+Os8uuZuuwtHECHM3EEwdsgnBgxNqga4cTXvXBFAdUDxH
            4r58DZlAwBwAR7yt23V275W6Z0baL+Quw3aWwZ0uf73JxSHjRCw2Xb+MISrMqz3S
            XAG9OUsnVDgKm4b6lJW1lciNmzz8I1/dT74rJd267Lx4TyiC1FCkxD5pmXcjUYf+
            vMo7MCbi2sQtcV19U8BP3vk6LWUs3sGIyyoMW6LjCWJetG4XXT3xuaVUk21u
            =XcRu
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
