apiVersion: v1
kind: Secret
metadata:
    name: minio-creds
    namespace: minio
type: Opaque
stringData:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:uo7qmWy+MDz/,iv:bL/zsXt75fmWwiU7uPp2gwvj9Szf+yQ2rjTGWHtLzRo=,tag:CiBfAGDIuHcqWcHSncSANA==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:eWrY3SKi0XV183OX9Wb0F8KD6ZXC08Sg12BH15d6aRU=,iv:Z2hMS428xs+Fd3TgylJWq7syp6NZyFqVqbm3mLpvgVc=,tag:BmS7vBWD8I2B9Zg3WAarXg==,type:str]
    config.env: ENC[AES256_GCM,data:2iAjJSjCIk4P/yc6lIUOFS7RtT8ibO6K4HBVUewDJmHfDc86Dl8npfu+IeDa+gCW6NY2xjSOYzuizCx8L71/anvgN6T/92QcKnCNinu1TmkJla9d7leJK1crww==,iv:+YQMZC+yyu8S8tho3oZAU4aN8NSrlkP9REf1S/oOjdw=,tag:HMLsNCZMfXZh9nFwnMvemQ==,type:str]
sops:
    lastmodified: "2025-09-28T20:40:37Z"
    mac: ENC[AES256_GCM,data:FfCuG4v2GIlj+wcTVz9EfX2uB11F/DrmtBnD+jVeCKb5yrlmndcZtCuq3cMUPmbv0UG2iQiIttv+wCq6qY2NzR3mmJJ60x1J3qqokNpjAzFEbPqnI7kgnnvbmdp+OUqehBkvEadrtgJRgf5KjXVH7fCM7xGcnLSy+h9oQTQqW7Q=,iv:N6L4m1x6VB7sEWRfhKCAG9+z8G4i93LLmsnW9/6AauM=,tag:NN7gyC5ydN9efyn9x+wx5g==,type:str]
    pgp:
        - created_at: "2025-09-28T20:40:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNARAA6HcMz5N0f7CDRbC46+lbX06B56ANaYH6h245WrAnB0NV
            YuSKi5wjm8Yb76olsm82RMpLEfOVzo9zQ5hoyPUKysX8DyipytipvfQG8plCwccn
            UynAt5TFZbY4G8POUlpZdgOKLvfqnp7wRAbEh+7N14RaiHJS1Z8PbpfkviytcKlp
            tcXxPdHZJtv9xE/py7W+qAkMOqZJq/poUgNpiwEOZRdpWLjsPqIKTuQQcWb91IDz
            mg3rL4SRL6fl4bZ9KUXUUmjhLGMbp+D4fjoB12evox0zQbBQz2BRHiJfogWF43z1
            pn4Kp96hGU0GDd3qk8JtP41AOkHXOCfqi93UXvCXr40Q34lqI3KhmJWyiCwe3CZC
            NQuhCJFJEPosS80VCwfn9Na4A/R3yIaN5785pQaNdYPEQ8OKzGYowH/PUVchP2/+
            5HIBQ1ayBLv//zPblsySNV9FAar+3/ow4f+VY+NP+wxQouYJe3CYkXxIvdINuVfZ
            /Rxh3E31XiY+rKrIxRaaxOweZvuZrQFhAzdRDkGdxbb8HuJtXR6/p1KqVamlIGtz
            Zpdzu5Wbxmjeh0MTojfdlXTXLBeMILQ1bNbEOk1uzStkrjPGIbguJn0Xrw0db3JZ
            cdqhHiyQd8YH8GOcKaney4cf6+/PucK7NU4c6rNh4/U7jwQVOZlkpDT4cgA4oavS
            XAGibDg5iRApCn4xdjMhlUKdKnM/cSDVx5lN1VqpXx/IU2xzrV5V67dUevUFBG4B
            X8J51yQjoB78fX1iWukPtSsmMzlzUdcc7uZ4gfPDrYZUEYfy4xe8kE9aiwi7
            =qCQi
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
