apiVersion: v1
kind: Secret
metadata:
    name: minio-creds
    namespace: minio
type: Opaque
stringData:
    accesskey: ENC[AES256_GCM,data:lgrh8kqkHXgC,iv:/GxOEsvLEu1ZyDOQUUk+nSX0/f2oqK4VouP6cGXcW+c=,tag:+B95Z1gt47uyuIwTkO7WcQ==,type:str]
    secretKey: ENC[AES256_GCM,data:kA2fHnHRkIdVpunsi6KSVYYKXmJCONLWRNmi8TMJJP8=,iv:hS1Bu+PlWfOz5jlHArCdsHkhkA+i96Z9Vqb1Kt5F7LM=,tag:BgKNdTCvfTvl52kEnSGwTQ==,type:str]
sops:
    lastmodified: "2025-09-28T18:27:35Z"
    mac: ENC[AES256_GCM,data:zUE87eEkLdOfK5XERFsqxshALeCMCs0ZavBR5kvhmibweDg+OSQMkz79GXaAF0fL50JntbodZ1zv5uZ8WFeEmE74tyif3l2+EqWWXA4ljJtJT6A/piLmu+h0A1n1nHnZL2UZe0HPr4HMnH9xXuyD/8CMH3BdFx8qXwSiLVQhmiI=,iv:Xw4MednuIsjkHFK/fjIFx4OG++VMoD/gcdU5GeafPFM=,tag:eQshgTHJzFAJ9xmnoTWR2A==,type:str]
    pgp:
        - created_at: "2025-09-28T18:27:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNARAAqjzhs77KGAEhOBOCDXerDYpmt2y5WbVoT9CeZvHcowkD
            gBVK39HLUrc7R40PrKeFXUiKCh2nMBSSX4RUECm938J1smqT+IKtyvQTNxNVV9tC
            R63jsF+QDaqAPToRAI+EgGKDQ8h5f4c+4M8CGYQ4EJMK1zRDMFro0JC5BsUtfW7K
            LGJ1mWOqsWYSEn5QqAkMn9blugPK5cItoMzgKNEBU8JEwSSmbHKXSjr5HTBQgFlS
            zAtryKT0s2TYp2VlgVp1lD8I5AtQYfg3JnzNBljtzrkWXXPjxIeigDHewoeSeZ5k
            iexxcmPJ6QX3KVjtnRALIEzr/jmAOR3wNYzfGVixbrngO4JhdxSHYyknW/bla9sV
            ElGcSo+MUzqhnyYmr0Z+h/IALjXtvFTnZ25O5IzL1zrTUs0SdtTIqthwBUPb+nla
            u1V8ozy1iIXCZWDw92wFPIKA4qdTaJt3jcQ1F2JtqLvjg9QodZ68awRLhlYbyAfx
            B3bMaMWxrcAyAZRs0u5xhy39U0/l9MbAmYqeZYFkSVv61a5PRN99SQ8bkkLtZPnu
            ZDSgw7Cc27UC69JN+PaR5lKgTnWSL/D49uA0/N/eoKvujBHNVnxSVef6lyj9p6eq
            oNA4rVa2LiGQXhG+OssX3G790OhhNynH4JuMhitSGsn1Wjmm2UQtpuTJ7w14nh7S
            XgHzuqTvQEu7Xw1423VWDentuQECV13LwNC4PXbucEDUn9VGhktFdsvykhsJ5bDC
            6vMDiizvKbizAQlDnK83vreywkq8Wfer25Jx4D25tpw2oSX+uE3ao8R4uK0AiaA=
            =rnzY
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
