apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: tenant
      version: "7.1.1"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    tenant:
      name: minio
      pools:
        - name: pool-0
          servers: 1
          users:
            - minio-creds
          volumesPerServer: 1
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              accessModes:
                - ReadWriteOnce
              storageClassName: zfs-local
              resources:
                requests:
                  storage: 10G
