apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
  namespace: minio
spec:
  requestAutoCert: false
  image: minio/minio:RELEASE.2025-09-07T16-13-09Z
  users:
    - name: minio-creds
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: zfs-local
          resources:
            requests:
              storage: 10G
  exposeServices:
    console: true
    minio: true
