apiVersion: v1
kind: Secret
metadata:
    name: minio-creds
    namespace: minio
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:yXSYPXxo2NSSuI3PKCCiHzTe7F2+PdndObjw4/BLGRYnXzWnLBzdeBDqGVDb6bEoRFAVCzZWFFpbrgokuk79qLmyBC9t+AmpocD+R5j8IHzj3bUAdqB6,iv:LUg1OrpTvXI0vfKa+o3xpodaz23JmMxlzuhX4nrMg3M=,tag:nOYxFnn9ImoTIP0fxJ0LxQ==,type:str]
sops:
    lastmodified: "2025-10-02T20:13:33Z"
    mac: ENC[AES256_GCM,data:2mj/7W8zcai1w3NrixmEwCGo4j8UVJ2rdTZCVGoQmjYQRzqq+BK2mZSS+QSeen2vZFLe780GzNa/calVjhfdXP2qaTv7Nnh0hgZMNXU6VYSMIOzifDwkU9SZvGSclsM2EYVqVkTIQTUfvTIYtv9CTAvEZbOUGley33Vho2Xkxs0=,iv:qar8jHloGZn/RXygaSrsXREhsysxAtN0mFDNgGJQ7Vk=,tag:hSUy7pmSuSKUv2itUaRYpA==,type:str]
    pgp:
        - created_at: "2025-10-02T20:13:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNARAAsancfKV/jKICFxWfdf1fHwqNk/+5mF68WA6HuN+V2ZnZ
            UTx+r9EWXqISwDjAMDIGnfm7sjmJ1CxgynXqJAV+b0g9opjWVVZtLodfeM+Ta7QY
            PcsG0nwstN79BMLE3WJJ6FKGynfj7A1ZtGekZNO0/+b/kBS1J3J93FmLi37tOMad
            v1ergxCkBOTl0coKnIt5egCiYK458Dk6XLYsKDXsF91uJMlek1Eg4k9ItMH+dKDW
            zKuELForGi4HmUUYgnTreobd3673bjZJc6LNHYJ0f5BbyX18WplMlXhULrYOH0M0
            vC7xMTRRZpREGuuejDVgl5rfXpynym+8Tc4NJA9UzAPvkjXWtys2Srsqg2i43JhR
            hISeHKB0x8LzIOcvmXJguxi3Kz+GfXmrAdq1SeHdBjJAP4Njn/tnUG/V1dC4vSMx
            ZbE2Vva+eJ6GZHlwicCpR+7RboV8c5USz2enom5PmqIpO/tsnEmI50aqtHHs7fwq
            irDsMwr9RY3vBRQNEm8bGtPy5YgSh4DIM2iy5XFrBbWf5Pf9OGoZSp9sJTsXzU9T
            +hNp9YGpw4p6+T5LUhPeUfICyXgo7ZlUiIhtpK249/XimOSqX8yxJ+EM/crUb/bV
            E5q1yBEeUeyqx3q+UUiChBcvpjeJrRR5mnpElOOZFXedroO1y4l7Z45DCgmfteLS
            XgGgtWWoyQfbUct7uR1McIm8vJjIAx74u9TT+m7vqxAgxXtT0UDDlDOnxzs3dX/P
            T/6O8W9tQvRsgDwPJYNcpLyT0WmT06IwAWm/7lWMdqQUW8FsgSWzcUylkzn5Yfs=
            =DpTF
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
