apiVersion: v1
kind: Secret
metadata:
    name: godaddy-api-key
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:fdhG51mtxH35S1v5+rG2L3f5lUAWIlT5vX3/SHPsxfMvhYY8EoWAO23lILSNWys2HlpL7TeNDOy8hQ==,iv:pkT6I19AOT7YhqJKj1ufEQ/++/Dk5GnZXtp9I2SnPUU=,tag:zGn9oLtHHCp179neal/RMw==,type:str]
sops:
    lastmodified: "2025-10-01T13:31:10Z"
    mac: ENC[AES256_GCM,data:++7HyTTpBdTQFzCILRKOGX2e48SPHAsa+F2fWItXYyJmJBRAlLI43FGmhcp1mPKHPEGmY8UtboU6PlrZDI0zc2efdnz4RQIbt/Re80tr+J9Bibd7xC6K7CsN9ASHEHfE9iz24udyFOto8IvqE2WdZzJKDCa0sUbQsVeDs7KGH5g=,iv:N3qCuWw6ojAG0ZzMIs/dBymN2uZfCZKl8L/pcHOJlj8=,tag:2eTkFO+hLFi+QumAO5B6Xw==,type:str]
    pgp:
        - created_at: "2025-10-01T13:31:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNAQ//Tunmo5o7szwC78Ew3TUOiQZH2CftiVChPmD5wwGPSsi0
            3elZriTPtMMW4vCRwnHAv6hsxmvVWZM+qdMgZnXAPGxgpfrDdWtXJEjmWaHJ1tRo
            zdy+FesJtHQegKz0nbXPlIJLtyHljlMm+MxP6ZvojZp/z4NnVDfh5fekK2oM2tDn
            cYT+PSfY4FMfFO9mUsfByW4o4xLu7SamO1qbJSeJYbi78TpjYnuBAb4xqwTEOLMj
            QMCng8xdfz3h/X7rpU3XkICd5UBSXi1lq4jNs9H/7Hx/qAPBd0ZAq3NBNh/lCKKb
            AJ8Tf5rgPq7udBsL81EYUxxmSBk8Vo0NXd3D5wncxkhWwAb0TmHKaIH17xA0iF1c
            qINr7m/RQjBVZo+9hRczcNLmFjdC8FT/UYdUfVsIZYvnqDVZZO5mI1zOq7RpohDa
            OzqOGohynTcgnvVNu9pQok5b16SLwkE3Qs6CHHpr312wvDeNVAAW9cD9lVaHcSgi
            HYYB5QZOl1d46od3T8wPQoKMlVgpsjUy6vQRiKjxBBl6qEd+47JF2aGcSyTHUx6Z
            tVYNEHyE43bZiBNrx8lrpB8T9N7kjfAN9e8/mFrYpSUoCy3bpXkdjquYWPqp1/kv
            UyUAJxCRTA1pZkMryQgEGj+mT8iVvwXANHJ49aRjO+zrHWUQ52ZL7i3S2UeRe+fS
            XAFbXA8C4Nuyz9emKeKKbmDhHS/JKnmuf3+znoa05Wqv8FRmRSkXvT53N4dHppXO
            XaO+F8ktaLTzMg0R88RiT+hAMggHonlwVY3Sj0FQt0StacEAEmcsC89No1TM
            =1tz6
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
