apiVersion: v1
kind: Secret
metadata:
    name: godaddy-api-key
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:p2OBOfSoLVsAeo5gnQDZxbFeAqIpuRqpxWlSJf91ow5hDPMIW9+vWs9PRdJm5csNStpT71/AEotdKQ==,iv:PHxUQeb1E+QYbSO5AGiJ1no9e4o1d5xGTs3PlKTTBkI=,tag:dOWmekF08lEDs5oZiFxS8A==,type:str]
sops:
    lastmodified: "2025-10-01T14:44:05Z"
    mac: ENC[AES256_GCM,data:zOFLX51NeIWIntoqTxnFn/LeDXai+NXxw6rcyB/sxYey0gJj1odv5FW6Q7nSRr/dhp7bdiFLomRg51u1joIfrr15+Rv7kWhbMzl20qXghEAn+c8OqxTEN7xmPHDng1aMhA+TMBT2WVOgfHWJDDFOAzQOZhln04ATuKwpXzJxb5c=,iv:5AjiRwWeItMWevZopJf09Mua7cCtN2h1egxlmSCUQgs=,tag:iibJ8kbNtxaVUGo27KECAQ==,type:str]
    pgp:
        - created_at: "2025-10-01T14:44:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNAQ/8D1EQXb/AI1FxkD79nPJSXXXwxvegqBMBP39VApvX921v
            KqAauZ0j/K3XUdFarrLrugVAXpGFuJGOGNXwefpJvrJ6GpTwLJPOXdpSruITQp4r
            J5hTz7xJHy3nyHczzb/pbvtCDieSVG9f/eSGptgVHKwSWyb10tyzOaSyyPKuT6jA
            UdgKw0MvkBemgtO7AXsqkjclRQ5qcb0QLXQwWG0MO1ENhNGu/whk4BSxJCrv9nFl
            9iuiDQiqyVJv0vwnP1MqVftiLBv+KdM3kwBGIgJX/Y6QZC1kzVpwiS/emhDmAvMf
            jP7VqHMo3f8nDgZHp3yq0I+QGk2GPb6NWuPC7f+fMdvHzfDRxNzadQARdwcjripr
            e3BzQz5n2Fw73xMANIqSXwOcKr6FE0XD0Tztoijh2DxfgYcKPIDdZrakiqYmxIB3
            GBY5E/QMykGxcsrPkNOgm+oD3cZK79Ag0I1Q8VZsTFUn/8ny1cPoE4Oq6wfivKYE
            fwX9M6BsmDzKgvZ/Zr5O+vRIfri2LzQ8oveuHF7vC2/yqbPaJmxJU7fYVtUO5oK8
            1zJxTWZQ3GIt8icDW53Ru8EBSNp+8VTq4QL1wfbP43Eoyttn6qcTR5MejqWTihZC
            hvCKhmklVgxGohLk4jJFn8fFmSoA1gkZ9NNFtgETgBIxqs36kBapQ1W6w+PlNeLS
            XAGR3AYqXXvXFQT8BbmnIvXae/Fl4nhC6nrvTsRg4RiCNWq8qhBKkz2yWzQqMmyS
            t+cOGI11QeIBspCMlW22XDoonIVe0mR9GkOCMOUNW2aEUgujPiIRUaJETuhL
            =PF9L
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
