apiVersion: v1
kind: Secret
metadata:
    name: godaddy-api-key
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:HCxcYzvUXKIG3Y1hG7qdE0vNMYJkejK81gMDEcdgF8d2amXlm5JWUE+Jl5+S7cAHsZs7K9yTgXVsvQ==,iv:QkVUMDbUSD4K8DQSXy2zONBf+Le36FxccNHpXE9tAMM=,tag:G8hkz1l/QCZEzRYjm/EzYw==,type:str]
sops:
    lastmodified: "2025-10-01T14:16:48Z"
    mac: ENC[AES256_GCM,data:InuvAj6BZ9hP8glH8iztURWMw4vlb+eQTETfGlqCFK2y4/AoOpIu6Yw2+UKC0ELUJsxNCVRLoSHPzZ5ZfdG6zMh6nv+K60ivtlcWnT9W/ihSlpnEJDSGdY/NciN09J+mg8YvF9urElmdkXy6zEBVVn1K+OJYvUhY+y3G/UVObE8=,iv:cKW+Q5l0/6xEKUtIsM0RQK/BraCMlmO7An6IxlWBwIY=,tag:hOMfP/gDiwFP+L6Vh4slmg==,type:str]
    pgp:
        - created_at: "2025-10-01T14:16:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNARAAvEMqEEr80iVCYqXtF/EDyA71vBlsgdhnzJTjM601J7Wd
            ZVvFs4rHobRqeXtnZTbLjm2pu35qg0iU8EwAtuAzO4H/vGlloeL6aaLZIoxpucSe
            Q92HmpcYuvL3amnHUFyiQdPkk+dTyQmRhzjRZNQzkp+VML8KGH3XEnhK7jmISAL0
            gcC++UV5cghoYKOZUO6jn/+EPXlrruwYH7/SHAdduTInH6uzn4P1o1XfTiB6qpfl
            ZJKoumLD0W0kDydQ2LxGYwOqmefEXYKU/iB7FVt1k+FP0V0/HGrjfpGYGFkx18fT
            ngBkGAP1Kc5MvV11vKty5uq3uKB48zePk7dRHv64uZKQKAqKA4dvtkiwDYKyToA/
            AaAH8udHex00PogXiuvSfBztMjqDA6/Yh7WfRdLpakFlWSKofZ4gp33j93vJIT5w
            8/Ixu5WohNmBTxPkTsrpu0alKfWBPk1lIiOXZo+we+XMe9xxyETLvdyoHQeimjKo
            b5eLU63wBc00BgCpWHBOdA28jyj878zdpqbhCXItkQCU/OFhnlXok3FIzECDGHG2
            BohY07I79up23EBa16sCyoBcL9yq5h1I3wqg8vvPVVWmAGxWUDYjqShh5ilLiJP0
            0DlfTHqV8CC4J/PNWioeHpsX5k2xHmCbKR7V4CDG4jCp8WgLFNE3Hf/50tlfwRTS
            XgHjWCi3BsWilBab5x1PGQxdGeSlV5ndSyp9cVIFOFtkfWzWT3hhQ575kl5ptlCn
            GuiGcGwgFEPq81zv3Z7lXdJJVvE+v5UoSNGA6Oth7Uq083WNQ2zm5VCkoYV4+es=
            =4wUQ
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
