apiVersion: v1
kind: Secret
metadata:
    name: godaddy-api-key
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:DxywFjmZXiWpuouxDeh6eYBIqeTiFkIFArchQtUKTPr4wakteh/eZ2QWaCTFGz1RIQk0x12zFqHPaQ==,iv:3tRtPVKWDkdxlDpf1F4PDJHi3BgRKtmtPS94Teo4LvA=,tag:7Eu+kiG9uQNNhttDTkrTLQ==,type:str]
sops:
    lastmodified: "2025-10-01T14:22:17Z"
    mac: ENC[AES256_GCM,data:9s9oAy6egthwwbDezxwpSGGl9QhvJMXtDRu6aceCk9H/NTDGo1zX6spc18apEkE2/2KoSmJ5UwesT4F2begiYkU5zdg9w5o9+bo/F/wb2gywG7b+4hv3UkAoLnT3KWQ68AktSMq2h30F5XZT0UmViT72oF+k7VLxMZ6r2aJE0es=,iv:FwTXqFU4Yl3izusmN8MbHomfJ6bjr05zJdq3qpf8Feg=,tag:v43bREB6UvICogwviKVyKw==,type:str]
    pgp:
        - created_at: "2025-10-01T14:22:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNAQ/8CswnnMqKetoK3sqtnFwjUL1eliFhLumbvuC+Wj7L0dt8
            NhYl/qG4Sxl2Pz2eqtdmBYP1rAN21cwzeiOz1J7fjMYECNX+hfzC3/oJ/ZsPeaQI
            XY4EqwE3vumvqAyNtewamLho9HQB1TUtLCtuS243rYw6RlW18qR/Aq7CAewVNgNu
            t26Fdzxwqx5siK9c9wKzxCH4nXJII9dg0FNlRYlVUE8p9plbe+TK23wqChAjQHOt
            bN/EeEh3yaOL6SUEEP8Evdl3iBaXWDifl19jK3rIMOBI9AEYQGTVb6BEnuhCu2/2
            3o2vdyG8JQ2i0juSoirT7yiZB4jlezRALApGZGQNpgvDsQ1kQJ4sbZU7jWYwiLGo
            qhlaePUNts8gwkzhBzAxzObp8PWF1tPhTPQkXjxLMj7pYH/3K2m5GWF4Dm9LZs0r
            /6jVv9a4zSUgOp7BEVH1p8oq2lm7bfGxhMNdScC+FDss4SpD/0YjLF4MOn0pN8hG
            v83xAmquecnXIDG3hTVGhCA0JbTZHp06X7Zsqn7HCPHtXnc63d6hWx63hPymwC27
            nBAkl0AND9pVmeSVanUpsdvDMoes/q6gp76p91hkV6bKMovW309n83SOM6sAWJlk
            z3MxgWTyf9CLLTb9OMMYgo01yRNnHSlhX7W2u7jxUhQIz1oC+lxwZjWka7RcwY/S
            XgGqPV1Djy5Bvq/c7jNbpvFaCe3bIhkRTJQNb77ihWeZPlVEPpIQ9JC4ndzuLkbG
            vTZXRxf+7NuZQuXGN09rbrN5WB7u9xxWP7JMliRR4C/8lJ1T87MdyDNxFEaYLmo=
            =7eNC
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
