apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:VeQMTrw=,iv:UZTVKpFy0+1tBzylqqyzL+ujTZLUf238p9CEoRi27aM=,tag:DDikv1cW99B586d8zWEr+Q==,type:str]
    admin-password: ENC[AES256_GCM,data:BaDLyLn2t69wwK9HjFg7af11AidCNa75iEQllcYlnuFOnhOJ7Zgw5mFz+v7iEPvszMzMw3DbkQW3kokPiAtsEw==,iv:ef7RWZ3Uo7x/e723u5bpsYS1ejQgpcFn7Nav1IdkVUk=,tag:K35sWmTfXe0tGH7GXKXhHA==,type:str]
sops:
    lastmodified: "2026-08-18T21:56:29Z"
    mac: ENC[AES256_GCM,data:SAVDKt/cRXodmwJfad76BRdLksJn4V59oFYqQ8PdRdiaMngrE+2GGAdsPCPZldo0iq2QEfydNjDnycoEWnj8BzSkK+ETjLecozTpt+0IPJTQHicUIvMXzFaVxAFo+q9opLnObNDs5DBDWO+E/S88e9sdilLqENU+ZGioshH4Pog=,iv:Qxvz5LwcHBt7nAf0hUaO3/eUCXV98H0A61FtgeGkZSw=,tag:qj5C+exmJv7toFBK2v7zTg==,type:str]
    pgp:
        - created_at: "2026-08-18T21:56:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNAQ/8DjyaeetxEuvh5Kiv8cIxAlcSITKG3XnNtPZ7HMntOVAe
            9eZz/YqZjX3v8BN8SldREyvQR4zuyKekQIjmt6tVH/bhkfQ5LOD/AipkyP+E90T4
            Bj/Y5Ytl8ICSBNWM4PyIbrgW1e1gS9KruTW4wmcy1O37ZYWerN1XzRtHprP2/TyE
            XwM+buqE+o5Y+gCokHM7t7jmHVwLaoyucpdZR1/qjx3r5sDeP9vhRjjBpZjNwiOX
            Ui3uDgfZPTqZ+m9CZcy8E6EMxwDt2cYHQzBC3GKmPbtTdlo4967uVTzCVIzenntz
            Qj9oG3KEMc+NDa4Yn2MWg/QCjp/8DbXE4yjYpwH2+EX4NrdDGqRo4kVxX5Zn/Pzx
            1TT9juvzob6gBVRxa36nZOHkcNqbm6ZNE1MbBf+0WDFiX4jAtONUJEzz08c7BHaD
            xoVijbWFiDRCbQcknj49QU68S2sORNCj2+xjs/EcgIppdeSa9d1VQbaOTSdGK+Ji
            VCTjL4CPxQp3A8RnoAl+gUbhGi+tRSwAILdmuBpVVAJf77r8DZ9sVJhoV5K1RNEx
            buP/1QTsnmh9qD0exAW5CAvNqOruMOTIL5IEt6+t8oBWxus8NYFMjGrpV8t6Mlgm
            +8cm0hQsLiobYiiKOdDaAlTxDQICHLpeT6IM61Isrn/mYiAfGoQOSP5xcKR1hDLS
            XgFzdgNIrgGX7zqiibiLbF9gktIDGlYN0dPCCSP2quZ8SP+WJrOANmMc6Hqd3rYH
            k9OuTiVfAe0Fa89dLuqAyirA1IKRAf5TzWZuig0mqphbZTaIU2a1gTVdAsHNpcw=
            =yhMI
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
