apiVersion: v1
kind: Secret
metadata:
    name: host-telemetry-ingest-auth
    namespace: observability
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:R+sFBllVw7lajlt3AkRF4SMMQvRS8Pic3tL+jzaIOag1sr1+lrqeQnSs+S16ZtO2J5ep0hdRZn7M9SeM2CvvY+92uP/gyvLuQlgYLroqBnfaWTNozR6mbglZK2hTeYPeRXofBnBU3jY4MUmzlzCy1au8STbbdLS0246HA5E4VDFH9Z9CW5OVPMtsBg==,iv:LeG4jbzhJu3boEhB4w+7ct9W9/z1AYZoWvSlE2tmU+g=,tag:Vn255RWBZPjQ8V0r48DBWw==,type:str]
sops:
    lastmodified: "2026-08-26T22:37:39Z"
    mac: ENC[AES256_GCM,data:YsrllWyho1FhLo2ZzppW8WNi61pQMsA17ncJyiKx0Q+x+B6d+CmTxCrVdaPlzTcBil6XbeQ2IaBVm6Lv4Gx0nCwzlEc4tQpxamq2/79JAL9B77AOdC2nU/US9U8Yl+RpOBhmxnSXw7DgNezj2SBUmXIEgd08z4jnLOdBc0Ik//s=,iv:wocCTAZcKZQ8LOl1PblvXm6ukEMTg13fW5DoJKNqh4s=,tag:dM6bhGdaZtKjmDUwy1WFQw==,type:str]
    pgp:
        - created_at: "2026-08-19T03:08:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNARAAlnehR8lFFrt73YcuPwmBFisUSgYQM5owMm4FWsONPqli
            pRC+M3P040pnbm03ABSRnrISqWlGltkvnTHogd94KXFRzspDTr9kqV7OwP0SaqQd
            rWY4mUi9o0khx8goTefmTDg2M7WtPvjdSdJaFt1/ZORmAlPEEIvEojEqpe762uL4
            A8WWKhs+Z/cd91owWpe673IFXzo+WPNITnlLu+oHK3XmsmRiwY/Ci9UlBhzp13dx
            cfW/wXNTPd6hRYts/TJSK8rpvUu7g3cyXsvIC/QB5initjtj2bAoELcLcSVZLUub
            2EC7C1xAmDZfN8lMBETZPDiFZn0kZRDcr3l1QSzZC4XPkYV+mCUzFxd5TXv1FFq7
            ty4vEJKH2T77Mz+IMW6IXLTD2LPqfS4IrRIpV3GCRwzdSH/jtI4qUvXKulh9H20w
            jju8MYR34bEugfV1pOD5aOaJce+Y5VgC4NSl3yxMeMuPDEt4f1pFmc+rwwqu4DhT
            fzJiqN1s2lK4u3Aijs8FUlIbGSssCKZNGjGEE7gHeuiSCth+DAbmJ/GcgbxHOjAB
            pXWuC198PRo/LSaRrKnszhiQBb8IDyVzaSNhJQhVJX8mN88emURpVnrE7fKo7uuU
            adrPMVy6ChH0Bh0LdlTaIAFZs3hIWSy4PpcOscwV560CwC3Mtftsg4xAVtNMZyrS
            XAECEl2M7uQTvOCZ4h/PdyeOUoacEZy6kRcg2isSz/i6jMJmymAwgsM/yAbB7cO/
            PeaNj+h+UjdPgc/1/GDPaznmBdeqcH2DTz2AMXXIzDzH3fLVxMHQjlDKFYpV
            =wL/a
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
