apiVersion: v1
kind: Secret
metadata:
    name: host-telemetry-ingest-auth
    namespace: observability
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:bRAVgRqcCL0X5defwy6dFBvJI/AmDQMVSweDkO3eCY0c/0B39SJuF6leao3VGmR3gK6IELcOBxLCd9U3fUNG11crWUELSxALtKP64H3MDLH1BgIbFFTtOEeVCs5Nluo1w5JwaOjj2UlwOpRZewTIAVm3uhHWJjzjOnTijag5OULQ2NY6a6WZW9wEwbBkPiReWDtPA73X6vz8N7z2m0MOWhu+eGadrshgA5oBsj59Wq6Z2Ev0KhAqellRZKYYcg1unMTfENXfNkZdKKyB4fylkdm2E++G6ZXxVA==,iv:WWBFimhZndssBnwgoyHhzxcUz8b3rtHnnLUKg/Hf8ag=,tag:sskP07ZwQFagUJKU02haMg==,type:str]
sops:
    lastmodified: "2026-08-26T23:29:28Z"
    mac: ENC[AES256_GCM,data:06HDRdW65FH06V3lVGvR0fpF3Fd/IVRCYFlPkOdeBAwiq9MKkPcUdwTg2d5Xjz4UQqoHq+74FRv/4FAA1DOn6fySjMkFhuS8jQrGAJX9JYWt7kcVVRI0j3kppgnFEBY4MH4bmE+iow8doX9ERh4JhsT1ioZUEJ8Wy+VWxOBUH/g=,iv:Y03/dpGiuxIZnVPOU49pbz41QyIP+J90Jeb33rPTmGg=,tag:XS+P1UPMgPQKIHigYxh9NA==,type:str]
    pgp:
        - created_at: "2026-08-19T03:08:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNARAAlnehR8lFFrt73YcuPwmBFisUSgYQM5owMm4FWsONPqli
            pRC+M3P040pnbm03ABSRnrISqWlGltkvnTHogd94KXFRzspDTr9kqV7OwP0SaqQd
            rWY4mUi9o0khx8goTefmTDg2M7WtPvjdSdJaFt1/ZORmAlPEEIvEojEqpe762uL4
            A8WWKhs+Z/cd91owWpe673IFXzo+WPNITnlLu+oHK3XmsmRiwY/Ci9UlBhzp13dx
            cfW/wXNTPd6hRYts/TJSK8rpvUu7g3cyXsvIC/QB5initjtj2bAoELcLcSVZLUub
            2EC7C1xAmDZfN8lMBETZPDiFZn0kZRDcr3l1QSzZC4XPkYV+mCUzFxd5TXv1FFq7
            ty4vEJKH2T77Mz+IMW6IXLTD2LPqfS4IrRIpV3GCRwzdSH/jtI4qUvXKulh9H20w
            jju8MYR34bEugfV1pOD5aOaJce+Y5VgC4NSl3yxMeMuPDEt4f1pFmc+rwwqu4DhT
            fzJiqN1s2lK4u3Aijs8FUlIbGSssCKZNGjGEE7gHeuiSCth+DAbmJ/GcgbxHOjAB
            pXWuC198PRo/LSaRrKnszhiQBb8IDyVzaSNhJQhVJX8mN88emURpVnrE7fKo7uuU
            adrPMVy6ChH0Bh0LdlTaIAFZs3hIWSy4PpcOscwV560CwC3Mtftsg4xAVtNMZyrS
            XAECEl2M7uQTvOCZ4h/PdyeOUoacEZy6kRcg2isSz/i6jMJmymAwgsM/yAbB7cO/
            PeaNj+h+UjdPgc/1/GDPaznmBdeqcH2DTz2AMXXIzDzH3fLVxMHQjlDKFYpV
            =wL/a
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
