apiVersion: v1
kind: Secret
metadata:
    name: livesync-member-credentials
    namespace: livesync
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:e8hpXaLaCWs=,iv:NJmqJI6JmMOy5MSJy88cjkXNB4O8bG+TvTLBRbrwpTg=,tag:mq6mco2TtpdH4QmIQl9drA==,type:str]
    password: ENC[AES256_GCM,data:YGVf1IAyM2B5mowBjPyPOz1lQwj5fm6Guc5PwEkogOny2RsBw4BSM0l8Oiuz5Odft43imCAewnr2vWFUlqYTfg==,iv:hoAxho3G8ZWO5VcG4KQCQ2aCEajkv4Phv/bt+o2rgJc=,tag:k3eRdO0b4utXRHK+oJDJgg==,type:str]
sops:
    lastmodified: "2026-08-22T14:53:40Z"
    mac: ENC[AES256_GCM,data:2LBLdtGW6/0UnL89FEccoOqFs9luMw1D6je0d4Q7ssId509dP/ldulAyY3grz+XUDWcJG6sGFwP4Cm5EquC2DdDPae+2zZ5djjVblkdPMre0090Kd2CQ4LaHZqoN4+RVzJLGBg6I7YPFRiox8E1MCCZTEGktkDDCZ1B7Ncvcrhg=,iv:MSqlzNtRLvNhJLUQ9nlyrmD18B+XbHU/VMj/chLACuY=,tag:DqHP8dMNQzLTHBNzKXUm/A==,type:str]
    pgp:
        - created_at: "2026-08-22T14:53:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNAQ/+KROulD3R258c/o1RURPOsss2WYivlBZBBBTB2sEf3HxW
            MjeniZ5Pqm3DPjPpmGQiqWOFZc4D8/Q2KdQnwRCNoN7E+UZuJRHvR0K8wYLvBg3L
            AjYTjskjv9zBy3ly0EH2kfgUWOdIrerO5FXIy7gdeXIhzrB8rKoyqofQcZNKN7sj
            WHRnh//re0Vt6QQa3BUZI0FQo+LJ/C7S08ax8SKpl3/fn46pdtLSYpGDoZ/oOetx
            mZ4ENejPP8OL5yYvqDubASH04o0l6RNmLYsjCpLtw3Z6jqfzzey+3Cen4jkgUcu4
            QfOfKlzT+7t0QQdMUvmaS5KVcCEtMybtL324TmEEopRIo2SAVJ2nRv1r3MveNTfd
            v0vy+WgozSVdjCJV0jOtJz8ERlPQXftEGeW73TJhgSA5lHVG9tbjR/OgYfAo+xg6
            M3JXKt0WzAtSHRjrkTD6Dvc0+H/YqDfiIi+U1SNZ6TTCfDrHJbgqipmvH5R9w+gY
            SjJFa+X5JS6rcKcl6PJJsWK7iawP8giY0m7QUT9i6vZvPqChZer69mT5pmApMfvs
            5DnP+ez8mPEFejkLEuojv6o9vFUarC3jY64ShMHC5MbUTFKUdk9AhSvLCs3g0WZJ
            1DIqOviVE4LHLdZMfB2edrejd+ZUKJGEmGXPmXOZeRC87XX9wVs9NMYRIO3pBkXS
            XgFMMIPXjIsPls2/C4+GmAI4wcRyej/awdAb0SI6qNUq8TTlvOi1rwap28cgWqil
            asKVFrPW96h2euqZ+3ToSESV/vSZ0e/j1V+gUt0A2qAQ/+ZSXO00ePDDcRJiXkM=
            =AX4k
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
