apiVersion: v1
kind: Secret
metadata:
    name: couchdb-admin-credentials
    namespace: livesync
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:npY5yKlFu3XzabQg+A==,iv:huIj2AQrpEUmuT2ouAaOl1+WV/ksidcykfk+MYKFjsA=,tag:DuDgItoaSpY8MEGx1c8J7g==,type:str]
    password: ENC[AES256_GCM,data:BpQMIjeiYbhfIC9J7GgDbTzglaQ16XisAulnBU5BrYDm9nsq4FgOTQd38JzB1+DLJSVLTmyT42zZDpXrn4fYDg==,iv:Yk0cd18aHwF4pH6UhigPOiIaRQCpmwiAOcRDkVWTs60=,tag:L+yhb2jFjMpND/sx2EroHA==,type:str]
sops:
    lastmodified: "2026-08-22T14:53:40Z"
    mac: ENC[AES256_GCM,data:fN+8D1XTW/TF2fEetdYClqgls8IRR5NcDD463+8Akzq9TB0vn1ty++88cwCEen9kobsEiq4zAgaoiNz9nqJpFQowX68Bu03JWsY6MMJXCImsczo5fMQscQ+2F6Tg54KDXOwkzUZVf9/OtJ/u6JILcuqI7VLVEvbE5GafuNFHUqE=,iv:ISG6sXILSc1WSkB+dxKOoeMiLDOiqgHJ/g7Qa0cT4LM=,tag:+WI6qdFXbQH+AL+SaYyCrw==,type:str]
    pgp:
        - created_at: "2026-08-22T14:53:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNAQ/+NNYAp/Wt6iZQpxa+ziNlE4DVrRWL39HAjIcqk/tILSTM
            A/b30dCjZwe8tNtS50SE6mMjutblgzNkIdZblZRiob/P0wTKt3A3mwxH4QpvBNOH
            bGOMhu3W8Z9YEttHaPT1/Hg+VLsX5FjL9ZM8wDuSVYxsfo2ubfkmcuVkk7HdLWCM
            aIxlOxA5Wb21p9iPwHX/lsjZSfgmwnNTMhdGxJhPbulquacJ+n268YptsqTzkLJ3
            0eIUzydfrF7WMXpcnEmzB7Bxu6HkTCQbcQB1ZIUxvRYBHUTGDxrseFC7jM/U4w0v
            pQtM2XOkMG+TZ13qWC5BTVdgcOnEdG6acPq/4iOCxmMv04yJooBZLYR/eIzs6dIi
            TxVcpAAOUHCSgGeleWID3I5rlwP2Xznf0TsdX5DiwAQSsGtaPjM9Ies7pkKEmsLK
            99nn1wrxmcvCQe/deMThPhIXmYggk4ROuKy/1qE/zgSVskPxiRoLEo149NgBR89n
            8DDG/4UqZwDzkI6hQDmnxa9Z2Jh20s+5aukbHAUYJDMgqGfSsCmEBM9eQ8IFo6WK
            wza7g2mL3u0vZPwaNkau315sh2FZYCnDCQBaySUITlnDlgQbtVyTQxpFbnKkj6nZ
            gLOp7W2fZ/HIK7t8Hi01zL91bOJtIXTQN/YRoHI8lhL6rR8GXjKVLhvPy7+xyerS
            XgEfk65sx/Xoe9WKTK9v3IRbz62S65vI4YPY7NVghrUHaGqYrsXN+et8OMv3esFI
            4hyiVhKxtDIigTTCunL3P/G9I9WixNOywBEHta+AQv8bdeDHTy+UijtENXWzR3M=
            =gDp7
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
