apiVersion: v1
kind: Secret
metadata:
    name: mimir-minio-user
    namespace: minio
type: Opaque
stringData:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:43/ghfxqaAvR+kkYODS7VQ==,iv:YgnHZTUIaZLjWSfMboH3i5Uf0QPUigolcP+zTMtTlGM=,tag:wsyZDmj8qSi8KLCoNwKKcA==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:afeKRjyyIPsev5T6l4MT92tJu/RELX690O+Down9N3o=,iv:XwTV44HPe6t9gJA+LkyEUvhWdog2JQVFgu/ohftDp4k=,tag:4TrF7ZcAAspfZMQfeaRMBQ==,type:str]
sops:
    lastmodified: "2025-10-05T18:03:44Z"
    mac: ENC[AES256_GCM,data:XS3j6DC/175xyxUE96O2xS2I0WVu/hcTD7KwCwcayORew2vW2lm2RsctZ/Z5LnpqjJ3eAW1YlbW0D3Up6/Uu0mPvDFO+Nnu9auEiasjCxF1/LuYkU32Qm0eWik3vzdVzjTzv/jWrax8kK0tZMEYEwAOeYmqRYytgSTvw4IZX54M=,iv:nQr8hXq62y1l3O0+OhyqCfgnzGGalUvQPxzGM2/UVYo=,tag:z9uGhMKW8XM+rgngUjTvXA==,type:str]
    pgp:
        - created_at: "2025-10-05T18:03:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNAQ//eTCbMxDNp/pYZKQiFaL0f6x+YcEDqL9TWz5kLsfytCQS
            SKRveX9J8aoV7E2kz5nsVtiQpnKiotFSegHrvsKOzKrrw0LKjn7jfHWIUac7bFo9
            RuLKqyAmfQkisqL5jwn/cZkidWFKp66giM00dGVz/A+hWGxAK/kU0+DRkQ/pXx2e
            UT98oeAzdWv7wFvo2UgC6+3m4g3tYiGF4MdjkNRE8n9sNdW6HRYm9h0N+1cFeBp2
            gVZHghHXeRHZ+Za09IbdsGriSWAFGUVXTx1abE4Z4KCT4wsFexJRCGmOzg6o0CRN
            Usyc9LwCkqg70uWeqvVb4MNjCeYda9OGa+KDekcOcjRB+kdq9i9DbiK5kOkJUAjB
            8Y8L3zDxIudijPVbgXrMJF+g1a2zdin2MU9iyUG9GhQTKeAvoK38znH25PrVcF1N
            pexzcJpasu6b2hrBlg+awXLfgKgFjBL45+1KZJpsBGrcEHfSnXxLDaFcR6XeKjzc
            PpuFG68mf1gtDe+IF6xEYH+Ip/LqvOJkRkisWxQU/zN5Ckd3bwsWxbnTQaM5X5Gn
            t4TQQosJUX6OH+f8s4v5yuWSolCLW7WwjTBz8GuNM67N0lKEuMaMBb4RPNo0WJmy
            gNC+Icb+Dzo/kjEUQaIleLeaoITKNp/8TALiKtz737DOW1tqnKUu+VD6lSBz1T3S
            XgEp5fWnaTXYn5ayZ2+JijQKj5olgzhzLnysFgboggi1BozspNkeGoUyUK02AI0Z
            d4AwDLcfqZZcx/9Nf2Mrpe5gJYNSO+P87PGSrFNYJXg6bib7Knp1J0ZUsPXDGac=
            =W8dx
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: mimir-minio-user
    namespace: observability
type: Opaque
stringData:
    access_key: ENC[AES256_GCM,data:RsIrNLj3KaE2VcMAVheuLw==,iv:y23ocKhOp7XGigOLOPvPUxF8zRglBw+rjsqGCp+B9LE=,tag:3sBp7KZxACnDxd/7pX/gfw==,type:str]
    secret_key: ENC[AES256_GCM,data:8fQcm+RCAVhi7ftk1D42i+4ufG4VpX5422+mJ+dCw/I=,iv:uLC7NnzQjiojL+8d+2G8oQjA5s6+kEDo4OuhCSBECBI=,tag:7GAl2ppjWojGY/CwvWaF8A==,type:str]
sops:
    lastmodified: "2025-10-05T18:03:44Z"
    mac: ENC[AES256_GCM,data:XS3j6DC/175xyxUE96O2xS2I0WVu/hcTD7KwCwcayORew2vW2lm2RsctZ/Z5LnpqjJ3eAW1YlbW0D3Up6/Uu0mPvDFO+Nnu9auEiasjCxF1/LuYkU32Qm0eWik3vzdVzjTzv/jWrax8kK0tZMEYEwAOeYmqRYytgSTvw4IZX54M=,iv:nQr8hXq62y1l3O0+OhyqCfgnzGGalUvQPxzGM2/UVYo=,tag:z9uGhMKW8XM+rgngUjTvXA==,type:str]
    pgp:
        - created_at: "2025-10-05T18:03:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNAQ//eTCbMxDNp/pYZKQiFaL0f6x+YcEDqL9TWz5kLsfytCQS
            SKRveX9J8aoV7E2kz5nsVtiQpnKiotFSegHrvsKOzKrrw0LKjn7jfHWIUac7bFo9
            RuLKqyAmfQkisqL5jwn/cZkidWFKp66giM00dGVz/A+hWGxAK/kU0+DRkQ/pXx2e
            UT98oeAzdWv7wFvo2UgC6+3m4g3tYiGF4MdjkNRE8n9sNdW6HRYm9h0N+1cFeBp2
            gVZHghHXeRHZ+Za09IbdsGriSWAFGUVXTx1abE4Z4KCT4wsFexJRCGmOzg6o0CRN
            Usyc9LwCkqg70uWeqvVb4MNjCeYda9OGa+KDekcOcjRB+kdq9i9DbiK5kOkJUAjB
            8Y8L3zDxIudijPVbgXrMJF+g1a2zdin2MU9iyUG9GhQTKeAvoK38znH25PrVcF1N
            pexzcJpasu6b2hrBlg+awXLfgKgFjBL45+1KZJpsBGrcEHfSnXxLDaFcR6XeKjzc
            PpuFG68mf1gtDe+IF6xEYH+Ip/LqvOJkRkisWxQU/zN5Ckd3bwsWxbnTQaM5X5Gn
            t4TQQosJUX6OH+f8s4v5yuWSolCLW7WwjTBz8GuNM67N0lKEuMaMBb4RPNo0WJmy
            gNC+Icb+Dzo/kjEUQaIleLeaoITKNp/8TALiKtz737DOW1tqnKUu+VD6lSBz1T3S
            XgEp5fWnaTXYn5ayZ2+JijQKj5olgzhzLnysFgboggi1BozspNkeGoUyUK02AI0Z
            d4AwDLcfqZZcx/9Nf2Mrpe5gJYNSO+P87PGSrFNYJXg6bib7Knp1J0ZUsPXDGac=
            =W8dx
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
