apiVersion: v1
kind: Secret
metadata:
    name: tempo-minio-user
    namespace: minio
type: Opaque
stringData:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:3nPm9FcrT0vGCi9aMZhc5g==,iv:QkHFhB6EdLMXHbUytuhZGnmlxpjliTcumq/EenJtc9Y=,tag:EyjAS6iGM+Buo3Rz2LBrPw==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:Eg7/6QU8S9G7LfwPbkKNI45jlChY4w6MyZZzrcWpjEu0+5sMt1yrbyU4XwkE1AO3SQimjawcWuS5hCJIdfED+w==,iv:6SNHH1XutnxBSralpKNOjOAzYkSLPLu4cAQZziIixIM=,tag:3gTLsV4vGH1/l6iVCHv/VQ==,type:str]
sops:
    lastmodified: "2026-08-18T13:18:56Z"
    mac: ENC[AES256_GCM,data:zjn+uM+lNx/ECOynAfoembp1naDEI1GeQiar7yLgiqDbHgod5lv9ZN5qspr+85xiMIz/77ti1ClcAj9xMN3wGiC/JxMuuHV2IFiPHE3DzNrvwlcvXj6mWWOBA2d2EoyD38OWUvwd8MlUfwyvW0Y34OeZq3vDBtZ3pg9u77o8TnU=,iv:KYJ56R2ekwEPhli+jrWHIz5K9l6d4Wt/o1Z2qXHIw2A=,tag:H4P9XnvPLG0Mhy8+m23IVg==,type:str]
    pgp:
        - created_at: "2026-08-18T13:18:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNAQ/+OvRJ4Qoa5/Feib9yC3fkLG75XMgbSw5rZfc8K8unelB6
            WY37K97OPDCgqqK0tq2FoscIbwKIIXl+3fUC3Qv35r6dG0B+ZKhvVnaqJLb3hS1W
            k4ibOPjIJO1uMVn5knK/3+kCl9JkU0B6czAlpsoRyQ1Z6vsuwcXnLPZ8H7hN1qYg
            W9QRFb/lZhoVXGUd9bre2RiPXc0sTNdhZvbbu2UmzmKiN6DPY4FE75KaA0rdetIx
            GxZ0ZLJusHlWpqR6e+dcTlLG3x39Oe/eNXghbjXXlH5xICCKWGW8vQ5s37E8Xqsh
            lwrvwCLargfJM4nkGrEIq/grcpbhSOFtE8EAHUZxYRCgm25H77IUVvyuW4xR+oCr
            CyqykwVi9hjGEN0oDIqh/iqAu2J2Grdk+N1GTEoZ3sQLH6ecGxySDeBmxWnFD1md
            cZ2MflwT0QgUXpj+Zii27Pfb9buSb6L64ahk4tdUcFr8e1qmQh2Uz5tgGZ6ZoDKT
            6OvLUxZXPcH5D9TYxNvOG3kI3pSuREu9C41nxvQSH6XlctA6wOCLHFav1lij6g3c
            b/kdyY7fc56UX0GDF5Wg7E64I6Rn9LelpmdgIVawG6Pdxe4LUhLB9D/rQBBmve8Y
            DDT1BCsSnICqBqGukZdONn2dSYcH3Z/1G0a1kpV58m++H+lVLPRksV2RgZbvl6rS
            XgEipOxgeuakMRhJ+R6QsZFZSCZSiBxjUabpHpGEv2uVHwzE1w9qt2ufqjK824jt
            icxVgFcKtjbBnOznjRy8ZM+x7QH9XnV3I+3YsMp6GOTk2K898sGB/VCMTaaKRew=
            =0E0y
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: tempo-minio-user
    namespace: observability
type: Opaque
stringData:
    access_key: ENC[AES256_GCM,data:nPYN39R0jdeS0efESlg9Cg==,iv:XH6wXk2T5xMLUWsnUzJXsidR+fNWHi1t4F1ucy3eX6s=,tag:WB4v1aRurFod/9INA9H6uA==,type:str]
    secret_key: ENC[AES256_GCM,data:mhXbazbugHCa14zcjPEtJNyxJX8zhLY8Qa8OdJYBwG6wuD4dGgUqgcFYUAT4+jzC2gA44PjMIFDL6Y0EFv9Ixw==,iv:DQ4o0y+KjS6EW9PsMw9trCxLyCmSeF7ixZkyMZuyPK4=,tag:NkkNHwpC4v72Q9LZhc19IQ==,type:str]
sops:
    lastmodified: "2026-08-18T13:18:56Z"
    mac: ENC[AES256_GCM,data:zjn+uM+lNx/ECOynAfoembp1naDEI1GeQiar7yLgiqDbHgod5lv9ZN5qspr+85xiMIz/77ti1ClcAj9xMN3wGiC/JxMuuHV2IFiPHE3DzNrvwlcvXj6mWWOBA2d2EoyD38OWUvwd8MlUfwyvW0Y34OeZq3vDBtZ3pg9u77o8TnU=,iv:KYJ56R2ekwEPhli+jrWHIz5K9l6d4Wt/o1Z2qXHIw2A=,tag:H4P9XnvPLG0Mhy8+m23IVg==,type:str]
    pgp:
        - created_at: "2026-08-18T13:18:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2ll/QoyK0oNAQ/+OvRJ4Qoa5/Feib9yC3fkLG75XMgbSw5rZfc8K8unelB6
            WY37K97OPDCgqqK0tq2FoscIbwKIIXl+3fUC3Qv35r6dG0B+ZKhvVnaqJLb3hS1W
            k4ibOPjIJO1uMVn5knK/3+kCl9JkU0B6czAlpsoRyQ1Z6vsuwcXnLPZ8H7hN1qYg
            W9QRFb/lZhoVXGUd9bre2RiPXc0sTNdhZvbbu2UmzmKiN6DPY4FE75KaA0rdetIx
            GxZ0ZLJusHlWpqR6e+dcTlLG3x39Oe/eNXghbjXXlH5xICCKWGW8vQ5s37E8Xqsh
            lwrvwCLargfJM4nkGrEIq/grcpbhSOFtE8EAHUZxYRCgm25H77IUVvyuW4xR+oCr
            CyqykwVi9hjGEN0oDIqh/iqAu2J2Grdk+N1GTEoZ3sQLH6ecGxySDeBmxWnFD1md
            cZ2MflwT0QgUXpj+Zii27Pfb9buSb6L64ahk4tdUcFr8e1qmQh2Uz5tgGZ6ZoDKT
            6OvLUxZXPcH5D9TYxNvOG3kI3pSuREu9C41nxvQSH6XlctA6wOCLHFav1lij6g3c
            b/kdyY7fc56UX0GDF5Wg7E64I6Rn9LelpmdgIVawG6Pdxe4LUhLB9D/rQBBmve8Y
            DDT1BCsSnICqBqGukZdONn2dSYcH3Z/1G0a1kpV58m++H+lVLPRksV2RgZbvl6rS
            XgEipOxgeuakMRhJ+R6QsZFZSCZSiBxjUabpHpGEv2uVHwzE1w9qt2ufqjK824jt
            icxVgFcKtjbBnOznjRy8ZM+x7QH9XnV3I+3YsMp6GOTk2K898sGB/VCMTaaKRew=
            =0E0y
            -----END PGP MESSAGE-----
          fp: F707507250DE30AFDBA89AA2AFE9B755DABFE17B
    encrypted_regex: ^(data|stringData)(..+)?$
    version: 3.10.2
