apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-repositories
  namespace: flux-system
spec:
  interval: 15m
  path: ./cluster/helm_repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
