apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: godaddy-webhook
  namespace: flux-system
spec:
  interval: 15m
  path: ./cluster/workloads/godaddy_webhook
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: secrets
    - name: namespaces
    - name: helm-repositories
    - name: cert-manager
