apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 15m
  path: ./cluster/workloads/tempo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: namespaces
    - name: helm-repositories
    - name: cert-manager
    - name: certificates
    - name: minio
