apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: host-telemetry
  namespace: flux-system
spec:
  interval: 15m
  path: ./cluster/workloads/host-telemetry
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: secrets
    - name: certificates
    - name: mimir
    - name: loki
    - name: tempo
