apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: godaddy-webhook
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: godaddy-webhook
      version: v0.5.0
      sourceRef:
        kind: HelmRepository
        name: godaddy-webhook
        namespace: flux-system
  install:
    createNamespace: true
  values:
    groupName: rafaeltab.com
